
x = [0,10,20,30,40,50,60,70,80,90,100];
y = fliplr([1,.8,.6,.4,.2,.0,0,0,0,0,0]);
graph   = line(x  , y   );

hXLabel = xlabel('a');
hYLabel = ylabel('\mu_{A}');

set(graph                          , ...
  'Color'           , [0.5 0 0]    );
set(graph                          , ...
  'LineWidth'       , 2           );

set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([ hXLabel, hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 18          );
set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );
x0=0;
y0=0;
xt = get(gca, 'XTick');
set(gca, 'FontSize', 18)
set(gcf, 'PaperPositionMode', 'auto');
print -depsc2 FMF_ex.eps
close;