
x = [0,10,20,30,40,50,60,70,80,90,100];
young = [1,.8,.6,.4,.2,.0,0,0,0,0,0];
middle_aged = [0,0.2,0.4,.6,.8,1,0.8,0.6,0.4,0.2,0];
old = fliplr(young);

young_line   = line(x  , young   );
middle_aged_line   = line(x  , middle_aged   );
old_line   = line(x  , old   );

hXLabel = xlabel('x');
hYLabel = ylabel('\mu_X');

hLegend = legend( ...
  [young_line,middle_aged_line, old_line], ...
  'Young' , ...
  'Middle aged'      , ...
  'Old'       , ...
  'location', 'NorthWest' );
set([hLegend, gca]             , ...
    'FontSize'   , 10           );

set(young_line                          , ...
  'Color'           , [0 0 .5]    );
set(middle_aged_line                          , ...
  'Color'           , [0 0.5 0]    );
set(old_line                          , ...
  'Color'           , [0.5 0 0]    );
set(young_line                        , ...
  'LineWidth'       , 2           );
set(middle_aged_line                        , ...
  'LineWidth'       , 2           );
set(old_line                        , ...
  'LineWidth'       , 2           );


set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([ hXLabel, hYLabel], ...
    'FontName'   , 'AvantGarde');
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 10          );
set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );

set(gcf, 'PaperPositionMode', 'auto');
print -depsc2 FMF_ex2.eps
close;