# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1132, 951)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 171, 901))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.sidebar = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.sidebar.setContentsMargins(0, 0, 0, 0)
        self.sidebar.setObjectName("sidebar")
        self.btnReset = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnReset.setObjectName("btnReset")
        self.sidebar.addWidget(self.btnReset)
        self.cbShowArrow = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.cbShowArrow.setObjectName("cbShowArrow")
        self.sidebar.addWidget(self.cbShowArrow)
        self.cbShowVisibility = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.cbShowVisibility.setObjectName("cbShowVisibility")
        self.sidebar.addWidget(self.cbShowVisibility)
        self.cbShowSector = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.cbShowSector.setObjectName("cbShowSector")
        self.sidebar.addWidget(self.cbShowSector)
        self.cbShowPath = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.cbShowPath.setObjectName("cbShowPath")
        self.sidebar.addWidget(self.cbShowPath)
        self.cbShowLights = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.cbShowLights.setObjectName("cbShowLights")
        self.sidebar.addWidget(self.cbShowLights)
        self.visibility = QtWidgets.QHBoxLayout()
        self.visibility.setObjectName("visibility")
        self.lblVisibility = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.lblVisibility.setObjectName("lblVisibility")
        self.visibility.addWidget(self.lblVisibility)
        self.numVisibility = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.numVisibility.setMaximum(1000000)
        self.numVisibility.setObjectName("numVisibility")
        self.visibility.addWidget(self.numVisibility)
        self.sidebar.addLayout(self.visibility)
        self.vessels = QtWidgets.QVBoxLayout()
        self.vessels.setObjectName("vessels")
        self.btnAddVessel = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnAddVessel.setObjectName("btnAddVessel")
        self.vessels.addWidget(self.btnAddVessel)
        self.sidebar.addLayout(self.vessels)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(170, 830, 961, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.horizontalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(170, 0, 961, 741))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(170, 740, 957, 35))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.slider = QtWidgets.QSlider(self.widget)
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.horizontalLayout_2.addWidget(self.slider)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(170, 770, 959, 79))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnPlay = QtWidgets.QPushButton(self.widget1)
        self.btnPlay.setObjectName("btnPlay")
        self.horizontalLayout.addWidget(self.btnPlay)
        self.btnPause = QtWidgets.QPushButton(self.widget1)
        self.btnPause.setObjectName("btnPause")
        self.horizontalLayout.addWidget(self.btnPause)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnReset.setText(_translate("MainWindow", "Reset"))
        self.cbShowArrow.setText(_translate("MainWindow", "Headings"))
        self.cbShowVisibility.setText(_translate("MainWindow", "Visibility"))
        self.cbShowSector.setText(_translate("MainWindow", "Sectors"))
        self.cbShowPath.setText(_translate("MainWindow", "Paths"))
        self.cbShowLights.setText(_translate("MainWindow", "Lights"))
        self.lblVisibility.setText(_translate("MainWindow", "Visibility"))
        self.btnAddVessel.setText(_translate("MainWindow", "Add Vessel"))
        self.label.setText(_translate("MainWindow", "Playback Speed"))
        self.btnPlay.setText(_translate("MainWindow", "Play"))
        self.btnPause.setText(_translate("MainWindow", "Pause"))

